### ISSUE TITLE
Getting error while installing via nvda-addon

### ISSUE THREAD

**Issue by Yeldece** [jscholes/nvda-speech-history#11]
In latest version i tried to install it via addon. It required restart, did, but in addons manager it showed as a required restart even i restarted my nvda. After bunch of restarts it didn't work and i check addons folder. There was a two folder speechhistory and speech history pending install. Deleted them, unzipped addon and copied manualy, and it worked after a restart.

**Comment by jscholes** [comment]
> it worked after a restart.

So what are you asking me to investigate, if the add-on is now working?  I can't look into every error from the add-ons subsystem, particularly when I don't have a log.
