### ISSUE TITLE
Say all restarts automatically with last NVDA alpha

### ISSUE THREAD

**Issue by CyrilleB79** [jscholes/nvda-speech-history#16]
Issue initially raised against NVDA but seems du to speech history add-on since it disappears when Speech History is disabled.

> ### Steps to reproduce:
> * Enable "Allow skim reading" in document formatting settings
> * Open a webpage, e.g. NVDA user guide.
> * Press control key to be sure to stop sayAll
> * Press H to go to next title
> 
> ### Actual behavior:
> NVDA reads the next title and then restarts in sayAll.
> 
> ### Expected behavior:
> NVDA reads the title and stops speaking.
> 
> ### System configuration
> #### NVDA installed/portable/running from source:
> From source
> 
> #### NVDA version:
> alpha-22222,2e37433e with the modification of [#12160 (comment)](https://github.com/nvaccess/nvda/issues/12160#issuecomment-811031134) to avoid crash.
> 
> #### Windows version:
> 10 1809
> 
> #### Name and version of other software in use when reproducing the issue:
> #### Other information about your system:
> ### Other questions
> #### Does the issue still occur after restarting your computer?
> Yes
> 
> #### Have you tried any other versions of NVDA? If so, please report their behaviors.
> 2020.4 is OK
>

**Comment by jscholes** [comment]
Thanks for reporting.  If/when this issue is reproduceable in a beta or RC build, I will look at fixing it.  Alternatively, it may have to wait until the next stable version of NVDA.

**Comment by CyrilleB79** [comment]
Closing this issue since it cannot be reproduce anymore with unofficial version of speech history modified by myself for compatibility with NVDA 2021.1.
I am not able to say what produced the change during alpha dev stage.
If this issue appears again in an official build of this add-on (hope coming soon), I will re-open this issue.
