### ISSUE TITLE
nvda-speech-history: NVDA 2022.1 compatibility

### ISSUE THREAD

**Issue by surfer0627** [jscholes/nvda-speech-history#31]
Note: this is a Add-on API compatibility breaking release. Add-ons will need to be re-tested and have their manifest updated.

* [NVDA 2022.1 available](https://www.nvaccess.org/download/nvda/releases/2022.1/nvda_2022.1.exe)

* [Changes for Developers | What's New in NVDA](https://www.nvaccess.org/files/nvda/releases/2022.1/documentation/changes.html)

* [repository: nvaccess/addonFiles: Community Add-ons website package hosting service](https://github.com/nvaccess/addonFiles)

cc: @jscholes

Thank you for your help.

**Comment by jscholes** [comment]
Closed via https://github.com/jscholes/nvda-speech-history/commit/c7e11aaa58815c38370a4a8f0b7033700136956a.

**Comment by surfer0627** [comment]
@jscholes,
thank you so much for your contributions.
