### ISSUE TITLE
Ability to have the speech history add-on in the add-on stor

### ISSUE THREAD

**Issue by GeorgeWu3** [jscholes/nvda-speech-history#35]
Hi, it will be nice to have the speech history add-on and the add-on store, Useful for those who want to download the add-on quickly without visiting any web page

**Comment by jscholes** [comment]
Thank you for your comments.  My experience of initially submitting Speech History to the Add-On Store was not a good one, but I do plan to revisit it at some point.  Probably when the next API-breaking release comes along in a few months.

I'll close this for now, given that having it open won't make me any more or less likely to do it, and I'll only forget to close it if/when I do.

**Comment by GeorgeWu3** [comment]
Nice, looking forward to it.
