### ISSUE TITLE
bug with Up and right arrows

### ISSUE THREAD

**Issue by comunicationVoices** [jscholes/nvda-speech-history#9]
For more information, visit NVDA issue 10865 where is this problem in the 2020.1 beta 1: https://github.com/nvaccess/nvda/issues/10865

**Comment by jscholes** [comment]
Thank you for the issue reference, but I have explicitly said that the add-on isn't compatible with 2020.1.  By the time 2020.1 stable is released, it will hopefully work.  Until then, this is a known problem.
